### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by anonyco** [joshmarinacci/voxeljs-next#33]
I and many others like me are new to Node modules. Please include command line snippets in the README about what to run in the terminal to start this server going.

**Comment by joshmarinacci** [comment]
Yeah, this really needs new docs. Also, its in the middle of a refactor. Also, to be clear, there is no server. Though it uses npm for module management it is entirely clientside.

**Comment by anonyco** [comment]
Perhaps you could setup gh-pages for everyone. Many people will appreciate a quick preview.

**Comment by joshmarinacci** [comment]
I just added a live preview and updated the docs in the README.md

**Comment by anonyco** [comment]
Thank you so much. The demo is spectacular. Don't forget to put a link to the demo up at the top (put a link to the demo in the Website box when you click "Edit" at the top of the page).

**Comment by joshmarinacci** [comment]
done

**Comment by srfoster** [comment]
This is great!  Thanks for the demo.

Just to confirm that it's working for me, can I double-check that my experience is the intended experience?  I ran into a few things that surprised me (as a Minecraft player) and caused me to think the demo was broken.  (I'm not saying it needs to be fixed -- just that it might be worth managing users' expectations by spelling out what the demo experience is suppose to be at this time.)

* **Unexpected.** ASDW do not do anything.
* **Unexpected.** Up and down arrow keys move you forward and backward, but left and right rotate the camera.  They do not strafe left and right. 
* **Unexpected.** Mouse movements do not move the camera.
* **Expected.**  Left click places a block; right click deletes a block.

**Comment by joshmarinacci** [comment]
Yes. Those are things which haven't been implemented yet.  You can see the arrow key bindings in the ecsy.html example.  It would be possible to add other bindings for WASD, however, I'm not sure this the "right way" to do input binding in a ECS system. I can add the other features easily, but just know that the API is likely to change.

**Comment by joshmarinacci** [comment]
I just pushed some big changes to the keyboard input system. It should be easy to customize the bindings now. Take a look at ecsy.html again.
