### ISSUE TITLE
Documentation + example errors

### ISSUE THREAD

**Issue by BobFred7** [joshmarinacci/voxeljs-next#35]
Where is the detailed documentation for `voxeljs-next`? Is there any?

Also, I tried to run the examples: `ecsy.html` worked fine, but `simple.html` has the player stuck in the ground and has repetitive warning messages, mainly `three.module.js:49083 THREE.BufferGeometry: .addAttribute() has been renamed to .setAttribute().`, and `networked.html` doesn't finish loading, giving some error message in the console about `Failed to resolve module specifier "three".` I preserved the directory structure from the repository download and ran a localhost static-file server to deal with crossorigin problems.

PS: when you left-click in the WebGL display/canvas area (in `simple.html`), the console gives an error message
```
TextureManager.js:194 Uncaught TypeError: Cannot read property 'findIndex' of undefined
    at TextureManager.getBlockTypeForName (TextureManager.js:194)
    at app.createBlock (simple.html:218)
    at ECSComp.js:13
    at Array.forEach (<anonymous>)
    at DesktopControls._fire (ECSComp.js:13)
    at HTMLCanvasElement.<anonymous> (DesktopControls.js:33)
getBlockTypeForName @ TextureManager.js:194
app.createBlock @ simple.html:218
(anonymous) @ ECSComp.js:13
_fire @ ECSComp.js:13
(anonymous) @ DesktopControls.js:33
```

**Comment by joshmarinacci** [comment]
There is currently no detailed docs. I'm in the process of migrating everything to the ECSY framework, so only the ecsy.html demo currently works. Don't use simple.html for now.
